name: Code Quality Checks

permissions:
  contents: write

on:
  # Run on every commit to main
  push:
    branches:
      - main

  # Run on every pull request
  pull_request:
    types: [opened, synchronize, reopened]

  # Run on every manual workflow dispatch
  workflow_dispatch:

# Cancel in-progress jobs when a new push is made to the same PR
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  main-checks:
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0

      - name: Install Node.js
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: 22

      - name: Setup Bun
        uses: oven-sh/setup-bun@735343b667d3e6f658f44d0eca948eb6282f2b76 # v2.0.2
        with:
          bun-version: latest

      - name: Install Dependencies
        run: bun install --development --frozen-lockfile

      - name: Run Type Check
        run: bun run typecheck

      - name: Run Lint
        run: bun run lint

  format:
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0

      - name: Install Node.js
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: 22

      - name: Setup Bun
        uses: oven-sh/setup-bun@735343b667d3e6f658f44d0eca948eb6282f2b76 # v2.0.2
        with:
          bun-version: latest

      - name: Install Dependencies
        run: bun install --development --frozen-lockfile

      - name: Format Code
        run: bun run format

      - name: Verify code is formatted
        run: git diff --exit-code
